apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ftp-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kpkqOrg/ftp-server.git
    targetRevision: HEAD
    path: manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: ftp-server

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
