name: Earth-app Push workflow

on:
  push:
    branches: main
    paths: 
    - ftp-server/
    - .github/workflows/push.yaml


jobs:
  deploy:
    runs-on: k8s-runner

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud auth configure-docker'
      - run: docker build ./ftp-server -t us.gcr.io/handy-geography-341716/ftp-server:$GITHUB_SHA
      - run: docker push us.gcr.io/handy-geography-341716/ftp-server:$GITHUB_SHA
      - run: ls
      - uses: kpkqOrg/actions/update-yaml@main
        with:
          filename: 'manifests/values.yaml'
          property-to-change: 'image.tag'
          value-to-change: ${{github.sha}}
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: manifests
